global using Bat.Core;
global using System.Reflection;
global using System.Linq.Expressions;
global using Microsoft.Data.SqlClient;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Query;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Microsoft.EntityFrameworkCore.ChangeTracking;